theme: minima
description: 1+AI Humans working with AI
title: 1+AI
description: Projects created by humans with AI
layout: home
linkedin_username: kashlik
twitter_username: kashleytwit
github_username:  kevinash
instagram_username: awesomeai_art